"""This modul contains all supported environment variables names"""

ENDPOINT_PREFIX = "ENDPOINT_PREFIX"
ALLOWED_CORS_ORIGINS_REGEX = "ALLOWED_CORS_ORIGINS_REGEX"
LOGGING_FORMAT = "LOGGING_FORMAT"
LOGGING_LEVEL = "LOGGING_LEVEL"
WEB_COMPONENT_HOST = "WEB_COMPONENT_HOST"
