apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    geodds.component: api
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    geodds.component: api
  type: LoadBalancer