apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    geodds.component: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      geodds.component: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        geodds.component: api
    spec:
      containers:
      - command:
        - ./../wait-for-it.sh
        - $(BROKER_SERVICE_HOST):5672
        - --
        - uvicorn
        - main:app
        - --host
        - 0.0.0.0
        - --port
        - '80'
        env:
          - name: DB_SERVICE_HOST
            value: $(DB_SERVICE_HOST)
          - name: BROKER_SERVICE_HOST
            value: $(BROKER_SERVICE_HOST)            
        envFrom:
        - secretRef:
            name: $(DB_SECRETS)
        - configMapRef:
            name: $(DB_CONFIG)
        - configMapRef:
            name: $(API_CONFIG)
        image: geolake-api:TAG
        name: api
        ports:
        - name: api-port
          containerPort: 80
        volumeMounts:
        - mountPath: /catalog
          name: catalog
          readOnly: true
        - mountPath: /data
          name: data
          readOnly: true
        - mountPath: /downloads
          name: downloads
          readOnly: true
      imagePullSecrets:
      - name: scalereg
      restartPolicy: Always
      volumes:
      - name: catalog
        persistentVolumeClaim:
          claimName: catalog
