apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    geodds.component: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      geodds.component: broker
  template:
    metadata:
      labels:
        geodds.component: broker
    spec:
      containers:
        - image: rabbitmq:3.9.25-management-alpine
          name: broker
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 256Mi
              cpu: 500m
          volumeMounts:
            - name: config
              mountPath: "/etc/rabbitmq/rabbitmq.conf"
              subPath: rabbitmq.conf
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: $(BROKER_CONFIG)
            items:
              - key: "rabbitmq.conf"
                path: "rabbitmq.conf"