apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    geodds.component: broker
spec:
  ports:
    - name: "broker"
      port: 5672
      targetPort: 5672
    - name: "http"
      port: 8080
      targetPort: 15672 
    - name: "metrics"
      port: 15692
      targetPort: 15692
  selector:
    geodds.component: broker
  type: LoadBalancer