apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    geodds.service: downloads
    environment: development
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
