apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: development
  name: executor
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: executor
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: '2'
            memory: 4Gi
      volumes:
      - persistentVolumeClaim:
          claimName: data
        name: data
      - persistentVolumeClaim:
          claimName: downloads
        name: downloads